name: Deploy to AWS ECS

on:
  push:
    branches:
      - main
env:
  AWS_REPOSITORY: hellowwolrdrepository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::069524097677:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin secrets.AWS_ECR
          docker build -t $AWS_REPOSITORY:$IMAGE_TAG .
          docker tag $AWS_REPOSITORY:$IMAGE_TAG secrets.AWS_ECR/$AWS_REPOSITORY:$IMAGE_TAG
          docker push secrets.AWS_ECR/$AWS_REPOSITORY:$IMAGE_TAG