name: Integration

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
  unit-test:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test